[package]
name = "rat_rs"
version = "0.1.0"
edition = "2018"

[lib]
name = "Rat"
path = "src/lib.rs"

[build-dependencies]
cmake = "0.1"

[[bin]]
name = "test_rat_rust"
path = "../../tests/test_rat_rust.rs"

[[bin]]
name = "test_rat_rust_iter"
path = "../../tests/test_rat_rust_iter.rs"

[[bin]]
name = "test_rat_rust_packets"
path = "../../tests/test_rat_rust_packets.rs"
